# Generated by Django 3.2.19 on 2023-07-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=32, verbose_name='任务')),
                ('status', models.SmallIntegerField(choices=[(2, '重要'), (1, '一般'), (2, '紧急')], default=1, verbose_name='级别')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dept.userinfo', verbose_name='负责人')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
