# Generated by Django 3.2.19 on 2023-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0006_auto_20230704_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='principal',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '重要'), (2, '紧急'), (1, '一般')], default=1, verbose_name='级别'),
        ),
    ]
