# Generated by Django 3.2.19 on 2023-07-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0007_auto_20230704_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '一般'), (2, '重要'), (3, '紧急')], default=1, verbose_name='级别'),
        ),
    ]
